### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by Seirdy** [isovector/marlo#21]
Since Marlo seems to be building up its own index, it should obey Robots.txt and search engine directives (x-robots-tag, `<meta name="robots">`,  `<link rel="canonical">`, the `link` HTTP header specifying a canonical location, etc.). This might require settling on a user-agent format.

**Comment by isovector** [comment]
Sorry for the traffic! I'll see about getting that implemented.

**Comment by Seirdy** [comment]
No worries, I don't have a problem with it. I'm just filing the issue because others might be more concerned.

**Comment by isovector** [comment]
robots.txt support is implemented in 56abd5f2a10ebd5606f907506fa3b16a725e127d which I figure is the most important to not annoy anyone. I've opened new issues for the other control mechanisms you've pointed me at. Thanks again for the info!

The useragent is `marlo/1.0 (+https://marlo.sandymaguire.me)` if you'd like to make any directives.
